name: 'Bundle size reporter'
description: 'Post bundle size difference compared to another branch'
inputs:
  paths:
    description: 'Paths to json file bundle size report or folder containing bundles'
    required: true
  onlyDiff:
    description: 'Report only different sizes'
    required: false
    default: 'false'

branding:
  icon: box
  color: green

runs:
  using: "node16"
  main: "dist/index.js"